Skywars kit rebalance
NucleoidMC/skywars pull request #6
Opened 2021-03-18 18:57 UTC by Ryyye

The old kits felt rather thrown together, hopefully the new ones will give each a bit of a more distinct play style. Obviously going to likely need further balancing after playing with them a bit.

2021-03-18 19:26 UTC, PotatoPresident requested changes

2021-03-18 19:26 UTC, PotatoPresident commented on src/main/resources/data/skywars/skywars_kits/archer.json
> -    {
Getting rid of arrows is interesting.

2021-03-18 19:26 UTC, PotatoPresident commented on src/main/resources/data/skywars/skywars_kits/alchemist.json
> -  "kit_name": "witch",
Was kinda going for mob themed kits. Doesn't have to be a a total match, just thought it was kinda fun

2021-03-18 19:26 UTC, PotatoPresident commented on src/main/resources/data/skywars/skywars_kits/archer.json
> -  "kit_name": "skeleton",
pillager maybe?

2021-03-18 19:26 UTC, PotatoPresident commented on src/main/resources/data/skywars/skywars_kits/constructor.json
> +  "kit_name": "constructor",
Maybe villager? or go specific and say like Stone Mason?

2021-03-18 19:26 UTC, PotatoPresident commented on src/main/resources/data/skywars/skywars_kits/constructor.json
> +  "armor": [
Full chain seems op to me

2021-03-18 19:26 UTC, PotatoPresident commented on src/main/resources/data/skywars/skywars_kits/fish.json
> -{
Maybe not a super useful kit, but I thought it was kinda fun with depth strider. Don't see a reason to remove

2021-03-18 19:26 UTC, PotatoPresident commented on src/main/resources/data/skywars/skywars_kits/rusher.json
>  {
I liked creeper kit, tnt is fun. Could maybe nerf with a few less tnt and restone. Trident should be a different, imo, drowned I guess

2021-03-18 19:26 UTC, PotatoPresident commented on src/main/resources/data/skywars/skywars_kits/slayer.json
> -  "kit_name": "enderman",
Not sure what's really happening here. I think enderman kit was mostly fine how it was. Maybe make axe a separate Vindicator kit.

2021-03-18 19:26 UTC, PotatoPresident commented on src/main/resources/data/skywars/skywars_kits/slime.json
> -{
Yeah this kit was op, hate to remove stuff though :P Maybe give the armor curse of binding?

2021-03-18 19:26 UTC, PotatoPresident commented on src/main/resources/data/skywars/skywars_kits/snowballer.json
> +  "kit_name": "snowballer",
Snow Golem

2021-03-18 19:26 UTC, PotatoPresident commented on src/main/resources/data/skywars/skywars_kits/snowballer.json
> +      "Count": 32
Seems like way to many to me. Also could maybe use a 10 second spawn cooldown, getting hit off right at the start is no fun

2021-03-18 19:26 UTC, PotatoPresident commented on src/main/resources/data/skywars/skywars_kits/speedster.json
> +  "kit_name": "speedster",
maybe Horse?

2021-03-18 19:26 UTC, PotatoPresident commented on src/main/resources/data/skywars/skywars_kits/zombie.json
> -  "kit_name": "zombie",
yeah this one can die

2021-03-18 19:26 UTC, PotatoPresident commented on src/main/resources/data/skywars/skywars_kits/speedster.json
> +    AttributeModifiers: [
this is wrong, but ill deal with it

2021-03-18 19:44 UTC, Ryyye commented on src/main/resources/data/skywars/skywars_kits/archer.json
> -    {
Imo starting with arrows encourages a campy play style.

2021-03-18 19:45 UTC, Ryyye commented on src/main/resources/data/skywars/skywars_kits/snowballer.json
> +      "Count": 32
I think that being able to pressure somebody immediately gives the kit a niche, and since they don't deal damage there's no long-term effect, but I agree that there was way too many.

2021-05-09 01:08 UTC, PotatoPresident approved these changes

2021-05-09 07:40 UTC, Gegy commented on src/main/resources/data/skywars/skywars_kits/baby.json
> +    AttributeModifiers: [
This JSON is invalid- I don't believe SBNT format can be used here.

2021-05-15 14:29 UTC, merged