Kit rebalances/fixes
NucleoidMC/skywars pull request #8
Opened 2021-05-15 18:43 UTC by Ryyye

-Removed baby zombie's stone sword, the speed from the armor gives it an advantage over other kits as is and the stone sword encourages aggressive play to an excessive extent.

-Added 3 water buckets to drowned. Not all maps have water, the gimmick of the kit being gated behind RNG could feel a bit lame.

-Increased cooldown on enderman's pearls to discourage teleporting to mid off the bat, hopefully encouraging more strategic use of the pearls.

-Removed fish, as it has no advantage over other kits.

-Removed slime, as the core idea draws away from combat, kits that do this tend to feel a bit lame as they go against the core gameplay of skywars. Knocking people off for a free kill is still an option for any kit.

2021-05-15 18:46 UTC, haykam821 requested changes
These kit changes completely make the enderman kit useless for getting to the center because the drowned kit can use a trident for movement just as well.

2021-05-15 18:57 UTC, Ryyye commented
> These kit changes completely make the enderman kit useless for getting to the center because the drowned kit can use a trident for movement just as well.

As I said in the description this is intended. Teleporting to the center with enderman tends to lead to a rather boring early game, as one person ends up with much of the loot. The pearls have plenty of uses outside of getting to mid.
Drowned's downside is that it's much riskier, with riptide it's much easier to mess up and fall, although it could potentially be nerfed down to riptide 2.

2021-05-17 17:34 UTC, PotatoPresident requested changes

2021-05-17 17:34 UTC, PotatoPresident commented on src/main/resources/data/skywars/skywars_kits/drowned.json
> +    {
3 buckets seems excessive. IMO you should be able to place one bucket and pick it back up before all the water is gone, adds a bit more difficulty.

2021-05-17 17:34 UTC, PotatoPresident commented on src/main/resources/data/skywars/skywars_kits/enderman.json
> +      "duration": 45
30 seconds is a LONG time. If you can't bridge to mid in 30 seconds that's your fault.

2021-05-17 17:34 UTC, PotatoPresident commented on src/main/resources/data/skywars/skywars_kits/fish.json
> -{
I mean, its a bit useless, but it doesn't ***hurt*** gameplay, no reason to remove.

2021-05-17 17:34 UTC, PotatoPresident commented on src/main/resources/data/skywars/skywars_kits/witch.json
> +        "Potion": "strong_harming"
You can probably make the lingering potion last longer somehow. I can deal with that though

2021-05-18 01:45 UTC, Ryyye commented on src/main/resources/data/skywars/skywars_kits/drowned.json
> +    {
I've removed one of them. The risk is high enough with only level 2 riptide that 2 water buckets seems fair, as it'd be pretty easy to accidentally fling yourself into the void. If it turns out overpowered once it's tested it could always be nerfed again.

2021-05-18 01:47 UTC, Ryyye commented on src/main/resources/data/skywars/skywars_kits/enderman.json
> +      "duration": 45
It entirely depends on the map. It's pretty easy to spend about a minute at spawn on a map like hive, or any map where there are secondary islands you can visit.
Rather than shortening the cooldown, I raised it a tiny bit, but added a third pearl, so you can exploit the pearls for easy mobility midgame rather than an early push.

2021-05-18 01:47 UTC, Ryyye commented on src/main/resources/data/skywars/skywars_kits/fish.json
> -{
I agree, but from an outsider's perspective 'fluff' kits can make the game look unpolished.

2021-05-18 01:49 UTC, Ryyye commented on src/main/resources/data/skywars/skywars_kits/witch.json
> +        "Potion": "strong_harming"
I would appreciate this, thanks. I think the splash potions could stay for follow up combos, although I suppose it comes down to how long the lingering potions last for. One of them could maybe be removed.

2022-02-03 14:28 UTC, ShockMicro commented
I'm personally vouching for this, it's been so long and Rye's changes here seem pretty good to me. I agree with most of their reasoning, maybe fish kit could be reworked into a pufferfish kit based around poison instead of being removed, but I'm good with all the other stuff.

2022-10-09 00:16 UTC, PotatoPresident approved these changes
Sure why not

2022-10-09 00:16 UTC, merged